version: "3"
services:
  jenkins:
    privileged: true
    build:
      context: ../../../Documents
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


  selenium:
    build:
      context: ../../../Documents
      dockerfile: selenium.Dockerfile
    volumes:
      - ./reports:/reports
    depends_on:
      - jenkins
    command: tail -f /dev/null